#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-oldest_supported_numpy
Version  : 2022.1.30
Release  : 6
URL      : https://files.pythonhosted.org/packages/bf/62/d66bdb697dc2f840a479c63cc4859176a110d07bd14fbc8c55b87c9c9dc4/oldest-supported-numpy-2022.1.30.tar.gz
Source0  : https://files.pythonhosted.org/packages/bf/62/d66bdb697dc2f840a479c63cc4859176a110d07bd14fbc8c55b87c9c9dc4/oldest-supported-numpy-2022.1.30.tar.gz
Summary  : Meta-package that provides the oldest NumPy that supports a given Python version and platform. If wheels for the platform became available on PyPI only for a more recent NumPy version, then that NumPy version is specified.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-oldest_supported_numpy-license = %{version}-%{release}
Requires: pypi-oldest_supported_numpy-python = %{version}-%{release}
Requires: pypi-oldest_supported_numpy-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
.. image:: https://img.shields.io/pypi/v/oldest-supported-numpy
:target: https://pypi.org/project/oldest-supported-numpy/
:alt: PyPI

%package license
Summary: license components for the pypi-oldest_supported_numpy package.
Group: Default

%description license
license components for the pypi-oldest_supported_numpy package.


%package python
Summary: python components for the pypi-oldest_supported_numpy package.
Group: Default
Requires: pypi-oldest_supported_numpy-python3 = %{version}-%{release}

%description python
python components for the pypi-oldest_supported_numpy package.


%package python3
Summary: python3 components for the pypi-oldest_supported_numpy package.
Group: Default
Requires: python3-core
Provides: pypi(oldest_supported_numpy)
Requires: pypi(numpy)

%description python3
python3 components for the pypi-oldest_supported_numpy package.


%prep
%setup -q -n oldest-supported-numpy-2022.1.30
cd %{_builddir}/oldest-supported-numpy-2022.1.30

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643583764
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-oldest_supported_numpy
cp %{_builddir}/oldest-supported-numpy-2022.1.30/LICENSE %{buildroot}/usr/share/package-licenses/pypi-oldest_supported_numpy/3ebc53e0371dd237a116db1afce9fc4aee2dccbe
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-oldest_supported_numpy/3ebc53e0371dd237a116db1afce9fc4aee2dccbe

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
